services:
  mc-server:
    image: itzg/minecraft-server:java8
    container_name: rlcraft-CHANGEME

    ports:
      - "25565:25565"

    volumes:
      - ./data:/data

    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      FORGE_VERSION: "14.23.5.2860"

      MEMORY: "10G"

      OVERRIDE_SERVER_PROPERTIES: "true"
      DIFFICULTY: "hard"
      MAX_TICK_TIME: "-1"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "true"
      VIEW_DISTANCE: "8"

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 10G

    healthcheck:
      test: ["CMD-SHELL", "netstat -lnt | grep -q 25565 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
