services:
  mc-server:
    image: itzg/minecraft-server:java21
    container_name: mc-purpur-CHANGEME
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data

    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "1.21.11"

      ONLINE_MODE: "TRUE"
      SERVER_PORT: "25565"
      SERVER_IP: "0.0.0.0"

      INIT_MEMORY: "2G"
      MAX_MEMORY: "10G"

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 10G

    healthcheck:
      test: ["CMD-SHELL", "netstat -lnt | grep -q 25565 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
